spring:
  application:
    name: fei-ai-agent
  profiles:
    active: local
  ai:
#    # application-local.yml中已配置
#    dashscope:
#      api-key: ""
#      chat:
#        options:
#          model: qwen-plus
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
#    vectorstore:
#      pgvector:
#      index-type: HNSW
#      distance-type: COSINE_DISTANCE
#      dimensions: 1536
#      max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
#    # application-local.yml中已配置
#  datasource:
#    url: jdbc:postgresql://公网地址:5432/数据库名
#    username: my_user
#    password: ""
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.fei.feiaiagent.controller
# knife4j 的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
## searchAPI(application-local.yml中已配置)
#search-api:
#  api-key:

